    <section id="tag-container">
      <div class="tag" id="tag-1">
        <figure>
          <img src="images/member-1.jpg" alt="member 1" id="tag-image-1" class="tag-image" />
        </figure>
        <div class="tag-text">
          <dl>
            <dt class="description-title">Member 1:</dt>
            <dd class="description-item">Name: Quoc Bao Pham</dd>
            <dd class="description-item">Student ID: s104077493</dd>
            <dd class="description-item">Course: Bachelor of Computer Science</dd>
            <dd class="description-item">
              <a class="email-link" href="mailto:104077493@student.swin.edu.au">Email: 104077493@student.swin.edu.au</a>
            </dd>
          </dl>
          <table class="table-1">
            <caption>
              <h1>Timetable  </h1>
            </caption>
            <tr class="table-header">
              <th scope="row">Hour/Day</th>
              <th scope="row">Monday</th>
              <th scope="row">Tuesday</th>
              <th scope="row">Wednesday</th>
              <th scope="row">Thursday</th>
              <th scope="row">Friday</th>
              <th scope="row">Saturday</th>
            </tr>
            <tr>
              <th scope="col">8:30am</th>
              <td class="cos10026">COS10026 Live Online</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">9:30am</th>
              <td class="cos10026">COS10026 Seminar</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">10:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">11:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col"> 12:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">1:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">2:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10009">COS10009 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="tag" id="tag-2">
        <figure>
          <img src="images/member-2.jpg" alt="member 2" id="tag-image-2" class="tag-image" />
        </figure>
        <div class="tag-text">
          <dl>
            <dt class="description-title">Member 2:</dt>
            <dd class="description-item">Name: Nguyen Hung Nguyen</dd>
            <dd class="description-item">Student ID: s104058197</dd>
            <dd class="description-item">Course: Bachelor of Computer Science</dd>
            <dd class="description-item">
              <a class="email-link" href="mailto:104058197@student.swin.edu.au">Email: 104077493@student.swin.edu.au</a>
            </dd>
          </dl>
          <table class="table-1">
            <caption>
              <h1>Timetable  </h1>
            </caption>
            <tr class="table-header">
              <th scope="row">Hour/Day</th>
              <th scope="row">Monday</th>
              <th scope="row">Tuesday</th>
              <th scope="row">Wednesday</th>
              <th scope="row">Thursday</th>
              <th scope="row">Friday</th>
              <th scope="row">Saturday</th>
            </tr>
            <tr>
              <th scope="col">8:30am</th>
              <td class="cos10026">COS10026 Live Online</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">9:30am</th>
              <td class="cos10026">COS10026 Seminar</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">10:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">11:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col"> 12:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">1:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">2:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10009">COS10009 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="tag" id="tag-3">
        <figure>
          <img src="images/member-3.jpg" alt="member 3" id="tag-image-3" class="tag-image" />
        </figure>
        <div class="tag-text">
          <dl>
            <dt class="description-title">Member 3:</dt>
            <dd class="description-item">Name: Minh Thanh Dang</dd>
            <dd class="description-item">Student ID: s103824041</dd>
            <dd class="description-item">Course: Bachelor of Computer Science</dd>
            <dd class="description-item">
              <a class="email-link" href="mailto:103824041@student.swin.edu.au">Email: 103824041@student.swin.edu.au</a>
            </dd>
          </dl>
          <table class="table-1">
            <caption>
              <h1>Timetable  </h1>
            </caption>
            <tr class="table-header">
              <th scope="row">Hour/Day</th>
              <th scope="row">Monday</th>
              <th scope="row">Tuesday</th>
              <th scope="row">Wednesday</th>
              <th scope="row">Thursday</th>
              <th scope="row">Friday</th>
              <th scope="row">Saturday</th>
            </tr>
            <tr>
              <th scope="col">8:30am</th>
              <td class="cos10026">COS10026 Live Online</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">9:30am</th>
              <td class="cos10026">COS10026 Seminar</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">10:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">11:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col"> 12:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">1:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">2:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10009">COS10009 Workshop</td>
              <td class="tne10004">TNE10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="tag" id="tag-4">
        <figure>
          <img src="images/member-4.jpg" alt="member 4" id="tag-image-4" class="tag-image" />
        </figure>
        <div class="tag-text">
          <dl>
            <dt class="description-title">Member 4:</dt>
            <dd class="description-item">Name: Trung Kien Nguyen</dd>
            <dd class="description-item">Student ID: s104053642</dd>
            <dd class="description-item">Course: Bachelor of Computer Science</dd>
            <dd class="description-item">
              <a class="email-link" href="mailto:104053642@student.swin.edu.au">Email: 104053642@student.swin.edu.au</a>
            </dd>
          </dl>
          <table class="table-1">
            <caption>
              <h1>Timetable  </h1>
            </caption>
            <tr class="table-header">
              <th scope="row">Hour/Day</th>
              <th scope="row">Monday</th>
              <th scope="row">Tuesday</th>
              <th scope="row">Wednesday</th>
              <th scope="row">Thursday</th>
              <th scope="row">Friday</th>
              <th scope="row">Saturday</th>
            </tr>
            <tr>
              <th scope="col">8:30am</th>
              <td class="cos10026">COS10026 Live Online</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">9:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">10:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">11:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">12:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">1:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">2:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="cos10009">COS10009 Workshop</td>
              <td class="empty-cell"></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="tag" id="tag-5">
        <figure>
          <img src="images/member-5.jpg" alt="member 5" id="tag-image-5" class="tag-image" />
        </figure>
        <div class="tag-text">
          <dl>
            <dt class="description-title">Member 5:</dt>
            <dd class="description-item">Name: Hoang Hieu Nguyen</dd>
            <dd class="description-item">Student ID: s104052762</dd>
            <dd class="description-item">Course: Bachelor of Computer Science</dd>
            <dd class="description-item">
              <a class="email-link" href="mailto:104052762@student.swin.edu.au">Email: 104052762@student.swin.edu.au</a>
            </dd>
          </dl>
          <table class="table-1">
            <caption>
              <h1>Timetable  </h1>
            </caption>
            <tr class="table-header">
              <th scope="row">Hour/Day</th>
              <th scope="row">Monday</th>
              <th scope="row">Tuesday</th>
              <th scope="row">Wednesday</th>
              <th scope="row">Thursday</th>
              <th scope="row">Friday</th>
              <th scope="row">Saturday</th>
            </tr>
            <tr>
              <th scope="col">8:30am</th>
              <td class="cos10026">COS10026 Live Online</td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">9:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10009">COS10009 Live Online</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">10:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">11:30am</th>
              <td class="empty-cell"></td>
              <td class="cos10026">COS10026 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col"> 12:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">1:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10004">COS10004 Lab</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
            <tr>
              <th scope="col">2:30pm</th>
              <td class="tne10004">TNE10004 Workshop</td>
              <td class="cos10009">COS10009 Workshop</td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
              <td class="empty-cell"></td>
            </tr>
          </table>
        </div>
      </div>
    </section>
