    <section id="body-container">
      <ul class="enhancement-list">
        <li class="enhancement-item" id="enhancement-1">
          <h3>Enhancement 1: </h3>
          <p>A slideshow to introduce products in Home Page</p>
          <a href="index.html#enhancement-1">Link to enhancement 1</a>
        </li>
        <li class="enhancement-item" id="enhancement-2">
          <h3>Enhancement 2: </h3>
          <p>Enhancement 2: Animations for icon in Product Page</p>
          <a href="product.html#ctn_4">Link to enhancement 2</a>
        </li>
      </ul>
    </section>
