    <section id="body-container">
      <ul class="enhancement-list">
        <li class="enhancement-item" id="enhancement-1">
          <h3>Enhancement 1: </h3>
          <p>Enhancement 1: Advanced results in Manage Page</p>
          <a href="manage.php#enhancement-1">Link to enhancement 1</a>
        </li>
        <li class="enhancement-item" id="enhancement-2">
          <h3>Enhancement 2: </h3>
          <p>Enhancement 2: Login function for manager</p>
          <a href="manage.php">Link to enhancement 2</a>
        </li>
      </ul>
    </section>
