    <section id="body-container">
      <ul class="enhancement-list">
        <li class="enhancement-item" id="enhancement-1">
          <h3>Enhancement 1: </h3>
          <p>Enhancement 1: Advanced results in Manage Page. To implement this, our team create different SQL query and retrieve data from database, plus a little of data processing.</p>
          <a href="manage.php#enhancement-1">Link to enhancement 1</a>
        </li>
        <li class="enhancement-item" id="enhancement-2">
          <h3>Enhancement 2: </h3>
          <p>Enhancement 2: Login and signup function for manager. To implement this, our team make use of sessions in php. When username and password is set in session, user could access to the manage page. If username and password isn't set, user must go through login page to log in. If they don't have an account, they could register for a new account.</p>
          <a href="manage.php">Link to enhancement 2</a>
        </li>
      </ul>
    </section>
