  <section id="body-container">
    <div id="products-scrollview">
      <div id="enhancement-1" class="scrollview-item">
        <input type="radio" name="radio-button" class="slider-radio" id="radio-1" checked />
        <input type="radio" name="radio-button" class="slider-radio" id="radio-2" />
        <input type="radio" name="radio-button" class="slider-radio" id="radio-3" />
        <input type="radio" name="radio-button" class="slider-radio" id="radio-4" />
        <input type="radio" name="radio-button" class="slider-radio" id="radio-5" />
        <div class="slider">
          <img alt="Monthly-1" src="images/product-4.png" />
          <img alt="Monthly-2" src="images/product-5.png" />
          <img alt="Monthly-3" src="images/product-6.png" />
          <img alt="Monthly-4" src="images/product-7.png" />
        </div>
        <div class="radio-container">
          <label for="radio-1" id="label-radio-1"></label>
          <label for="radio-2" id="label-radio-2"></label>
          <label for="radio-3" id="label-radio-3"></label>
          <label for="radio-4" id="label-radio-4"></label>
        </div>
        <h3>Monthly Plans</h3>
      </div>
      <div id="fortnight-products" class="flex-center scrollview-item">
        <img src="images/product-3.png" alt="Product 2" class="product-image" />
        <h3>Earth Plan</h3>
      </div>
      <div id="monthly-products-1" class="flex-center scrollview-item">
        <img src="images/product-4.png" alt="Product 3" class="product-image" />
        <h3>Mars Plan</h3>
      </div>
      <div id="monthly-products-2" class="flex-center scrollview-item">
        <img src="images/product-7.png" alt="Product 4" class="product-image" />
        <h3>Uranus Plan</h3>
      </div>
      <button class="btn-1" onclick="window.location='product.html'">PRODUCTS</button>
    </div>
    <div id="articles">
      <article id="article-1" class="article">
        <h2 class="article-content">Having any questions?</h2>
        <p class="article-content">Feel free to ask questions about our products.</p>
        <button class="article-button" onclick="window.location='enquire.html'">Make your enquiry</button>
        <img class="article-image" src="images/article-1.png" alt="Nameless team">
      </article>
      <article id="article-2" class="article">
        <h2 class="article-content">About Nameless team</h2>
        <p class="article-content">We are a team of five people, each with abilities to perform different tasks. We all come with a great passion in programming, and willing to learn anything new. </p>
        <a href="https://youtu.be/s7elIFsZCEs">Watch the demo of our website</a>
        <button class="article-button" onclick="window.location='about.html'">More about us</button>
        <img class="article-image" src="images/article-2.jpg" alt="Nameless team">
      </article>
    </div>
  </section>
