    <section id="card-container" class="flex-container1">
      <div class="row">
        <div class="card-border">
          <img
            class="card-img"
            src="images/product-1.png"
            alt="Product 1"
          />
          <h2 class="card-title">MERCURY PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 30 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 20GB bonus data</h5>
                      <p>
                        Get an additional 20GB bonus data each month for use in
                        Oz when you stay connected to this plan. New and
                        additional services only. Offer ends 31/12/2022 unless
                        extended. T&C apply.
                        <sup
                          ><a
                            href="https://www.vodafone.com.au/tablets/sim-only?fbclid=IwAR1LABTRrX4u5zHqMtgA7X-fEML4Ikms_XltidKu2h1ijzj7GSnE7_kZDCE"
                            >[1]</a
                          ></sup
                        >
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="card-border">
          <img
            class="card-img"
            src="images/product-2.png"
            alt="Product 2"
          />
          <h2 class="card-title">VENUS PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 30 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 10GB bonus data</h5>
                      <p>
                        Get 10GB bonus data each month for use in Oz when you
                        stay connected to this plan. New and additional services
                        only. Offer ends 31/12/2022 unless extended. T&C apply.
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="card-border">
          <img
            class="card-img"
            src="images/product-3.png"
            alt="Product 3"
          />
          <h2 class="card-title">EARTH PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 60 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 40GB bonus data</h5>
                      <p>
                        Get an additional 40GB bonus data each month for use in
                        Oz when you stay connected to this plan. New and
                        additional services only. Offer ends 31/12/2022 unless
                        extended. T&C apply.
                        <sup
                          ><a
                            href="https://www.vodafone.com.au/tablets/sim-only?fbclid=IwAR1LABTRrX4u5zHqMtgA7X-fEML4Ikms_XltidKu2h1ijzj7GSnE7_kZDCE"
                            >[1]</a
                          ></sup
                        >
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="card-border">
          <img
            class="card-img"
            src="images/product-4.png"
            alt="Product 4"
          />
          <h2 class="card-title">MARS PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 60 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 20GB bonus data</h5>
                      <p>
                        Get 20GB bonus data each month for use in Oz when you
                        stay connected to this plan. New and additional services
                        only. Offer ends 31/12/2022 unless extended. T&C apply.
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="card-border">
          <img
            class="card-img"
            src="images/product-5.png"
            alt="Product 5"
          />
          <h2 class="card-title">JUPITER PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 180 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 80GB bonus data</h5>
                      <p>
                        Get an additional 80GB bonus data each month for use in
                        Oz when you stay connected to this plan. New and
                        additional services only. Offer ends 31/12/2022 unless
                        extended. T&C apply.
                        <sup
                          ><a
                            href="https://www.vodafone.com.au/tablets/sim-only?fbclid=IwAR1LABTRrX4u5zHqMtgA7X-fEML4Ikms_XltidKu2h1ijzj7GSnE7_kZDCE"
                            >[1]</a
                          ></sup
                        >
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="card-border">
          <img
            class="card-img"
            src="images/product-6.png"
            alt="Product 6"
          />
          <h2 class="card-title">SATURN PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 180 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 40GB bonus data</h5>
                      <p>
                        Get 40GB bonus data each month for use in Oz when you
                        stay connected to this plan. New and additional services
                        only. Offer ends 31/12/2022 unless extended. T&C apply.
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="card-border">
          <img
            class="card-img"
            src="images/product-7.png"
            alt="Product 7"
          />
          <h2 class="card-title">URANUS PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 365 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 120GB bonus data</h5>
                      <p>
                        Get an additional 120GB bonus data each month for use in
                        Oz when you stay connected to this plan. New and
                        additional services only. Offer ends 31/12/2022 unless
                        extended. T&C apply.
                        <sup
                          ><a
                            href="https://www.vodafone.com.au/tablets/sim-only?fbclid=IwAR1LABTRrX4u5zHqMtgA7X-fEML4Ikms_XltidKu2h1ijzj7GSnE7_kZDCE"
                            >[1]</a
                          ></sup
                        >
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="card-border">
          <img
            class="card-img"
            src="images/product-8.png"
            alt="Product 8"
          />
          <h2 class="card-title">NEPTUNE PLAN</h2>
          <div class="card-description">
            <ul>
              <li>
                <h4>Additional data</h4>
                <p>
                  Once you've used your included data, you'll automatically be
                  charged $10 for each additional 10GB ($0.001/MB)
                </p>
              </li>
              <li>
                <h4>Network Guarantee</h4>
                <p>
                  Take 1365 days to decide if you love our network with our
                  "Network Satisfaction Guarantee".
                </p>
                <p>Check the coverage in your area. T&C apply.</p>
              </li>
            </ul>
            <button class="dropdown-button">More</button>
            <div class="dropdown-content">
              <ul>
                <li>
                  <h4>Offers</h4>
                  <ul>
                    <li>
                      <h5>Get an additional 60GB bonus data</h5>
                      <p>
                        Get 60GB bonus data each month for use in Oz when you
                        stay connected to this plan. New and additional services
                        only. Offer ends 31/12/2022 unless extended. T&C apply.
                      </p>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
