
   <nav id="taskbar">
      <a href="index.php" id="logo-container">
        <img src="styles/images/logo.png" alt="Nameless" id="logo" />
      </a>
      <div id="taskbar-icon">
        <button class="btn-2" onclick="window.location='index.php'">
          Home
        </button>
        <button class="btn-2" onclick="window.location='product.php'">
          Products
        </button>
        <button class="btn-2" onclick="window.location='enquire.php'">
          Enquiry
        </button>
        <button class="btn-2" onclick="window.location='about.php'">
          About
        </button>
        <button class="btn-2" onclick="window.location='enhancements2.php'">
          Enhancements
        </button>
        <button class="btn-2" onclick="window.location='manage.php'">
          Manage
        </button>
      </div>
    </nav>

