    <div id="ctn_1">
      <h1 id="product-title">MOBILE PHONE PLANS</h1>
    </div>
    <div id="ctn_2">
      <p class="para_0">
        Whatever your needs, our NamelessNet Plans are tailored to suit you. Our
        Ultra+ Plan has unlimited mobile data at the fastest speed the
        NamelessNet network can deliver to your phone at the time and place
        you’re accessing data in Oz. Alternatively, choose a plan with heaps of
        Max Speed data and then you can keep using infinite data in Oz at speeds
        of up to 2 or 10Mbps, depending on your chosen plan. For more
        information on what you can and can’t do at these speeds, check out our
        speed guide. Once you’ve picked the right no lock-in plan, choose a new
        phone and pay for it interest free over 12, 24 or 36 months.

      </p>
      <aside>
          If your NamelessNet mobile phone plan is cancelled, you’ll need to pay
          off your phone on your next bill.
          <sup><a href="https://www.vodafone.com.au/plans">[1]</a></sup>
      </aside>
    </div>
    <div id="ctn_3">
      <h2 id="description-title">Why choose NamelessNet</h2>
      <div id="ctn_4">
        <div id="ctn_4_1">
          <img src="styles/images/icon-1.png" alt="5G" class="description-icon" />
          <p class="para_1">The #1 Global 5G Network.</p>
          <p>
            NamelessNet 5G rolling out in selected areas. The NamelessNet brand
            has a 5G presence in 200 countries and territories.
          </p>
        </div>
        <div id="ctn_4_2">
          <img
            src="styles/images/icon-2.png"
            alt="Like"
            class="description-icon"
          />
          <p class="para_1">Network Guarantee</p>
          <p>
            Take 30 days to decide if you love our network with our Network
            Guarantee. T&C apply.
          </p>
        </div>
        <div id="ctn_4_3">
          <img
            src="styles/images/icon-3.png"
            alt="Roaming"
            class="description-icon"
          />
          <p class="para_1">$5 Roaming</p>
          <p>
            Use only Max Speed data, calls and text in over 100 countries for $5
            extra a day. Countries may vary. T&C apply. Find out more.
          </p>
        </div>
      </div>
    </div>
