    <table class="table-2">
      <tr>
        <th>PLAN</th>
        <th>EXPIRY</th>
        <th>DATA</th>
        <th>INFINITE DATA</th>
        <th>UNLIMITED <br />CALL & TEXT</th>
        <th>DATA BANK</th>
        <th>INTERNATIONAL <br />TALK ZONE 1</th>
        <th>INTERNATIONAL <br />TALK ZONE 2</th>
      </tr>
      <tr>
        <td>15$</td>
        <td>7 days</td>
        <td>25GB</td>
        <td>-</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>25$</td>
        <td>fornight</td>
        <td>35GB</td>
        <td>-</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>35$</td>
        <td>fornight</td>
        <td>45GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>500 mins</td>
        <td>-</td>
      </tr>
      <tr>
        <td>45$</td>
        <td>month</td>
        <td>55GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>1000 mins</td>
        <td>100 mins</td>
      </tr>
      <tr>
        <td>55$</td>
        <td>month</td>
        <td>65GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>1500 mins</td>
        <td>200 mins</td>
      </tr>
      <tr>
        <td>65$</td>
        <td>month</td>
        <td>75GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>2000 mins</td>
        <td>250 mins</td>
      </tr>
      <tr>
        <td>155$</td>
        <td>month</td>
        <td>85GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>2500 mins</td>
        <td>300 mins</td>
      </tr>
      <tr>
        <td>1000$</td>
        <td>year</td>
        <td>155GB</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>&#9745;</td>
        <td>3000 mins</td>
        <td>350 mins</td>
      </tr>
    </table>
